version: '3.9'

services:
  next-app: 
    image: node
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached 
    ports:
      - 4000:3000
    command: npm run dev